version: '3.1'
services:
  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=andriy
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - /mongodata:/data/db
    ports: 
      - '27017-27019:27017-27019'
  api:
    build: ./api
    depends_on: 
      - database
    ports: 
      - '49161:8080'
  app:
    build: ./app
    depends_on: 
      - api
    ports: 
      - '49160:8080'